// Generated by CoffeeScript 1.3.3
var FileList, Q, glob, globQ, log, util,
  __slice = [].slice,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Q = require('q');

glob = require('glob');

globQ = Q.nbind(glob);

util = require('./util');

log = require('./logger').create('file-list');

FileList = (function() {

  function FileList() {
    var patterns;
    patterns = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    this.clear();
    this.include.apply(this, patterns);
  }

  FileList.prototype.clear = function() {
    this.includes = [];
    return this.excludes = [];
  };

  FileList.prototype.include = function() {
    var pattern, patterns, _i, _len;
    patterns = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (Array.isArray(patterns[0])) {
      patterns = patterns[0];
    }
    if (patterns.length > 0) {
      log.info('Including patterns:', patterns);
    }
    for (_i = 0, _len = patterns.length; _i < _len; _i++) {
      pattern = patterns[_i];
      this.includes.push(pattern);
    }
    return this;
  };

  FileList.prototype.exclude = function() {
    var pattern, patterns, _i, _len;
    patterns = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (Array.isArray(patterns[0])) {
      patterns = patterns[0];
    }
    if (patterns.length > 0) {
      log.info('Excluding patterns:', patterns);
    }
    for (_i = 0, _len = patterns.length; _i < _len; _i++) {
      pattern = patterns[_i];
      this.excludes.push(pattern);
    }
    return this;
  };

  FileList.prototype.resolve = function(pattern, basePath) {
    if (util.isUrlAbsolute(pattern)) {
      return Q.resolve([pattern]);
    } else {
      return globQ(pattern, {
        cwd: basePath
      });
    }
  };

  FileList.prototype.merge = function(fileLists) {
    var file, fileList, files, _i, _j, _len, _len1;
    files = [];
    for (_i = 0, _len = fileLists.length; _i < _len; _i++) {
      fileList = fileLists[_i];
      for (_j = 0, _len1 = fileList.length; _j < _len1; _j++) {
        file = fileList[_j];
        if (__indexOf.call(files, file) < 0) {
          files.push(file);
        }
      }
    }
    return files;
  };

  FileList.prototype.subtract = function(set1, set2) {
    var item, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = set1.length; _i < _len; _i++) {
      item = set1[_i];
      if (__indexOf.call(set2, item) < 0) {
        _results.push(item);
      }
    }
    return _results;
  };

  FileList.prototype.getFiles = function(basePath) {
    var excludedFileListPromises, excludedFilesPromise, includedFileListPromises, includedFilesPromise, pattern, promise;
    includedFileListPromises = (function() {
      var _i, _len, _ref, _results;
      _ref = this.includes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pattern = _ref[_i];
        _results.push(this.resolve(pattern, basePath));
      }
      return _results;
    }).call(this);
    excludedFileListPromises = (function() {
      var _i, _len, _ref, _results;
      _ref = this.excludes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pattern = _ref[_i];
        _results.push(this.resolve(pattern, basePath));
      }
      return _results;
    }).call(this);
    includedFilesPromise = Q.all(includedFileListPromises).then(this.merge);
    excludedFilesPromise = Q.all(excludedFileListPromises).then(this.merge);
    return promise = Q.all([includedFilesPromise, excludedFilesPromise]).spread(this.subtract);
  };

  return FileList;

})();

exports.FileList = FileList;
